def printinstruksi():
    print()
    print("---------------------------------------------------------")
    print("        SELAMAT DATANG DI PROGRAM OPERASI MATRIKS")
    print("---------------------------------------------------------")
    print()
    print("AVM Group E :")
    print("- Aliif Arief Maulana")
    print("- Anggito Wicaksono")
    print("- Niki Hidayati")
    print("- Ninis Dyah Yulianingsih")
    print()
    print("---------------------------------------------------------")
    print("               INSTRUKSI DALAM PROGRAM")
    print("---------------------------------------------------------")

    print("ketik 1 : program penambahan matriks")
    print("ketik 2 : program pengurangan matriks")
    print("ketik 3 : program perkalian matriks")
    print("ketik 4 : program trace matriks")
    print("ketik 5 : program transpose matriks")
    print("ketik 6 : program determinan matriks")
    print("ketik 7 : program invers matriks")
    print("ketik 8 : program penyelesaian persamaan linear metode Gauss Jordan")
    print("ketik exit : untuk keluar dari program")

    print("---------------------------------------------------------")
    print()